export { FaqPage } from "./faq"
export { Home } from "./Home"
export { Historia }from "./Historia"
export { GuiaTalles} from "./GuiaTalles"
export { TerminosCondiciones } from "./TerminosCondiciones"
export { PoliticasPrivacidad } from "./PoliticasPrivacidad"
export { ShoppingCart } from "./ShoppingCart"
export { ListProducts } from "./ListProducts"
export { Checkout } from "./Checkout"